training_games:
- data_feb_25/coverage_verified.jsonl
- data_feb_25/coverage_unverified.jsonl
validation_games:
- data_feb_25/eval_verified_incomplete.jsonl
image_size: 256
agent_outputs: "actions"
model_name_or_path: "Qwen/Qwen2.5-VL-7B-Instruct"
output_dir: "/data/tir/projects/tir3/users/svadugur/multi-modal-cad/models-deepspeed/qwen-action-all"
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
lora_enable: true
vision_lora: true
lora_rank: 128
lora_alpha: 32
gradient_checkpointing: true
gradient_accumulation_steps: 1
bf16: true
eval_strategy: "no"
eval_steps: 1
save_strategy: "epoch"
save_steps: 1
logging_strategy: "steps"
logging_steps: 1
num_train_epochs: 10
agent_outputs: "actions"
warmup_steps: 10
freeze_llm: true
freeze_vision_tower: true
learning_rate: 0.0001
remove_unused_columns: false